# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-24 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursoprofesor',
            options={'ordering': ['curso', 'profesor'], 'verbose_name': 'Usuari@s por curso'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'usuari@', 'verbose_name_plural': 'usuari@s'},
        ),
    ]
