# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-02 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170124_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, help_text='Teléfonos de contacto', max_length=50, verbose_name='Teléfonos'),
        ),
    ]
