# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(db_index=True, help_text='Curso Académico', max_length=9, unique=True, verbose_name='Curso')),
                ('retrasos_amonestacion', models.PositiveSmallIntegerField(default=2, help_text='Número de retrasos que generan una amonestación', verbose_name='Número de retrasos para amonestación')),
                ('retrasos_trimestre', models.BooleanField(default=True, help_text='Considerar retrasos en trimestres', verbose_name='Retrasos por trimestres')),
                ('inicio_primer_trimestre', models.DateField(help_text='Fecha de inicio del primer trimestre', verbose_name='Fecha inicio primer trimestre')),
                ('fin_primer_trimestre', models.DateField(help_text='Fecha de fin del primer trimestre', verbose_name='Fecha fin primer trimestre')),
                ('inicio_segundo_trimestre', models.DateField(help_text='Fecha de inicio del segundo', verbose_name='Fecha inicio segundo trimestre')),
                ('fin_segundo_trimestre', models.DateField(help_text='Fecha de fin del segundo trimestre', verbose_name='Fecha fin segundo trimestre')),
                ('inicio_tercer_trimestre', models.DateField(help_text='Fecha de inicio del tercer trimestre', verbose_name='Fecha inicio tercer trimestre')),
                ('fin_tercer_primer_trimestre', models.DateField(help_text='Fecha de fin del tercer trimestre', verbose_name='Fecha fin tercer trimestre')),
                ('slug', models.CharField(max_length=9, unique=True, verbose_name='Slug')),
            ],
            options={
                'ordering': ['curso'],
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
            },
        ),
    ]
