# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0002_auto_20161019_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoDepartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursodepartamentos', to='cursos.Curso')),
            ],
            options={
                'verbose_name': 'Departamentos por curso',
                'ordering': ['curso__curso', 'departamento__departamento'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('departamento', models.CharField(db_index=True, max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'departamento',
                'verbose_name_plural': 'departamentos académicos',
                'ordering': ['departamento'],
            },
        ),
        migrations.AddField(
            model_name='cursodepartamento',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='departamentos.Departamento'),
        ),
        migrations.AlterUniqueTogether(
            name='cursodepartamento',
            unique_together=set([('curso', 'departamento')]),
        ),
    ]
