# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-23 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        ('departamentos', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursodepartamentoprofesor',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='users.CursoProfesor'),
        ),
        migrations.AddField(
            model_name='cursodepartamento',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='cursos.Curso'),
        ),
        migrations.AddField(
            model_name='cursodepartamento',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='departamentos.Departamento'),
        ),
        migrations.AddField(
            model_name='cursodepartamento',
            name='jefe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jefaturas', to='users.CursoProfesor'),
        ),
        migrations.AlterUniqueTogether(
            name='cursodepartamentoprofesor',
            unique_together=set([('curso_departamento', 'profesor')]),
        ),
        migrations.AlterUniqueTogether(
            name='cursodepartamento',
            unique_together=set([('curso', 'departamento')]),
        ),
    ]
