# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 09:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departamentos', '0002_cursodepartamento_jefe'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoDepartamentoProfesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('curso_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursodepartamentosprofesores', to='departamentos.CursoDepartamento')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['curso_departamento__curso', 'profesor__username'],
                'verbose_name': 'Profesores por Departamentos y curso',
            },
        ),
        migrations.AlterUniqueTogether(
            name='cursodepartamentoprofesor',
            unique_together=set([('curso_departamento', 'profesor')]),
        ),
    ]
