# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0003_auto_20161019_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursodepartamentoprofesor',
            options={'ordering': ['curso_departamento__curso', 'profesor'], 'verbose_name': 'Profesores por Departamentos y curso'},
        ),
    ]
