# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0006_auto_20161019_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
