# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-23 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rayuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tipo', models.CharField(choices=[('PR', 'Profesores XML Rayuela'), ('AL', 'Alumnos ZIP Rayuela'), ('DA', 'Datos adicionales alumnos ODS rayuela'), ('TU', 'Datos de tutores legales ODS rayuela')], max_length=2)),
                ('archivo', models.FileField(upload_to='rayuela/%Y/%m/%d')),
                ('procesado', models.BooleanField(default=False)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.Curso')),
            ],
            options={
                'verbose_name_plural': 'importacion rayuela',
                'ordering': ['-curso', '-created'],
                'verbose_name': 'rayuela',
            },
        ),
    ]
