# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-23 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('codigo_centro', models.CharField(max_length=15, unique=True)),
                ('nombre_centro', models.CharField(max_length=50, unique=True)),
                ('url_centro', models.URLField(blank=True)),
                ('email_centro', models.EmailField(blank=True, max_length=254)),
                ('direccion_centro', models.CharField(blank=True, max_length=200)),
                ('telefono_centro', models.CharField(blank=True, max_length=200)),
                ('fax_centro', models.CharField(blank=True, max_length=200)),
                ('nombre_director', models.CharField(blank=True, max_length=50)),
                ('firma_director', models.ImageField(blank=True, upload_to='configies')),
                ('logo_centro', models.ImageField(blank=True, upload_to='configies')),
                ('sello_centro', models.ImageField(blank=True, upload_to='configies')),
                ('curso_defecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursos.Curso')),
            ],
            options={
                'verbose_name_plural': 'configies',
                'ordering': ['nombre_centro'],
                'verbose_name': 'configies',
            },
        ),
    ]
