# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nie', models.CharField(db_index=True, max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('usuario_rayuela', models.CharField(blank=True, max_length=20)),
                ('foto', models.ImageField(blank=True, default='', upload_to='alumnos')),
            ],
            options={
                'verbose_name_plural': 'alumno/as',
                'verbose_name': 'alumno/a',
                'ordering': ['apellidos', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CursoAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='alumnos.Alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursoalumnos', to='cursos.Curso')),
            ],
            options={
                'ordering': ['alumno__apellidos', 'alumno__nombre'],
            },
        ),
        migrations.AlterIndexTogether(
            name='alumno',
            index_together=set([('apellidos', 'nombre')]),
        ),
        migrations.AlterUniqueTogether(
            name='cursoalumno',
            unique_together=set([('curso', 'alumno')]),
        ),
    ]
