# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-23 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nie', models.CharField(db_index=True, max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('dni', models.CharField(blank=True, db_index=True, help_text='Número del DNI', max_length=20, verbose_name='D.N.I.')),
                ('direccion', models.CharField(blank=True, help_text='Dirección', max_length=200, verbose_name='Dirección')),
                ('codigo_postal', models.CharField(blank=True, help_text='Código Postal', max_length=10, verbose_name='Código Postal')),
                ('localidad', models.CharField(blank=True, help_text='Localidad', max_length=100, verbose_name='Localidad')),
                ('provincia', models.CharField(blank=True, help_text='Provincia', max_length=100, verbose_name='Provincia')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('usuario_rayuela', models.CharField(blank=True, max_length=20)),
                ('foto', models.ImageField(blank=True, default='', max_length=200, upload_to='alumnos')),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('expediente', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'alumno/as',
                'ordering': ['apellidos', 'nombre'],
                'verbose_name': 'alumno/a',
            },
        ),
        migrations.CreateModel(
            name='CursoAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='alumnos.Alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='cursos.Curso')),
            ],
            options={
                'ordering': ['curso', 'alumno'],
                'verbose_name': 'Alumn@s por curso',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('dni', models.CharField(db_index=True, max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('domicilio', models.CharField(blank=True, max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('municipio', models.CharField(blank=True, max_length=50)),
                ('provincia', models.CharField(blank=True, max_length=50)),
                ('foto', models.ImageField(blank=True, default='', upload_to='tutores')),
                ('telefono1', models.CharField(blank=True, max_length=50)),
                ('telefono2', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('alumnos', models.ManyToManyField(blank=True, related_name='tutores', to='alumnos.Alumno')),
            ],
            options={
                'verbose_name_plural': 'tutores',
                'ordering': ['apellidos', 'nombre'],
                'verbose_name': 'tutor/a',
            },
        ),
        migrations.AlterIndexTogether(
            name='alumno',
            index_together=set([('apellidos', 'nombre')]),
        ),
        migrations.AlterIndexTogether(
            name='tutor',
            index_together=set([('apellidos', 'nombre')]),
        ),
        migrations.AlterUniqueTogether(
            name='cursoalumno',
            unique_together=set([('curso', 'alumno')]),
        ),
    ]
