# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_auto_20161018_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('dni', models.CharField(db_index=True, max_length=15, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=100)),
                ('domicilio', models.CharField(blank=True, max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('municipio', models.CharField(blank=True, max_length=50)),
                ('provincia', models.CharField(blank=True, max_length=50)),
                ('foto', models.ImageField(blank=True, default='', upload_to='tutores')),
                ('telefono1', models.CharField(blank=True, max_length=50)),
                ('telefono2', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('alumnos', models.ManyToManyField(to='alumnos.Alumno')),
            ],
            options={
                'ordering': ['apellidos', 'nombre'],
                'verbose_name_plural': 'tutores',
                'verbose_name': 'tutor/a',
            },
        ),
        migrations.AlterModelOptions(
            name='cursoalumno',
            options={'ordering': ['alumno__apellidos', 'alumno__nombre'], 'verbose_name': 'Alumno/as por curso'},
        ),
        migrations.AlterIndexTogether(
            name='tutor',
            index_together=set([('apellidos', 'nombre')]),
        ),
    ]
