# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_auto_20161018_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
