# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0006_auto_20161018_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='apellidos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
