# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0007_auto_20161018_1808'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cursoalumno',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='cursoalumno',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='cursoalumno',
            name='curso',
        ),
        migrations.DeleteModel(
            name='CursoAlumno',
        ),
    ]
