# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0010_auto_20161020_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='foto',
            field=models.ImageField(blank=True, default='', max_length=200, upload_to='alumnos'),
        ),
    ]
