# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0011_auto_20161020_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='codigo_postal',
            field=models.CharField(blank=True, help_text='Código Postal', max_length=10, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección', max_length=200, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='dni',
            field=models.CharField(blank=True, db_index=True, help_text='Número del DNI', max_length=20, verbose_name='D.N.I.'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='localidad',
            field=models.CharField(blank=True, help_text='Localidad', max_length=100, verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='provincia',
            field=models.CharField(blank=True, help_text='Provincia', max_length=100, verbose_name='Provincia'),
        ),
    ]
