# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0012_auto_20161021_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='expediente',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
