# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-23 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CursoGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'ordering': ['curso__curso', 'grupo__grupo'],
                'verbose_name': 'Grupos por curso',
            },
        ),
        migrations.CreateModel(
            name='CursoGrupoAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'ordering': ['curso_grupo__curso', 'curso_grupo__grupo', 'curso_alumno__alumno'],
                'verbose_name': 'Alumn@s por curso y grupo',
            },
        ),
        migrations.CreateModel(
            name='CursoGrupoProfesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('curso_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesores', to='grupos.CursoGrupo')),
            ],
            options={
                'ordering': ['curso_grupo__curso', 'curso_grupo__grupo', 'curso_profesor__profesor'],
                'verbose_name': 'Profesor@s por curso y grupo',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('grupo', models.CharField(db_index=True, max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'grupos académicos',
                'ordering': ['grupo'],
                'verbose_name': 'grupo',
            },
        ),
    ]
