# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0002_auto_20161019_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursogrupos', to='cursos.Curso')),
            ],
            options={
                'ordering': ['curso__curso', 'grupo__grupo'],
                'verbose_name': 'Grupos por curso',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('grupo', models.CharField(db_index=True, max_length=10, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(max_length=10, unique=True)),
            ],
            options={
                'ordering': ['grupo'],
                'verbose_name_plural': 'grupos académicos',
                'verbose_name': 'grupo',
            },
        ),
        migrations.AddField(
            model_name='cursogrupo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='grupos.Grupo'),
        ),
        migrations.AlterUniqueTogether(
            name='cursogrupo',
            unique_together=set([('curso', 'grupo')]),
        ),
    ]
