# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-23 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        ('grupos', '0001_initial'),
        ('users', '0001_initial'),
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursogrupoprofesor',
            name='curso_profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='users.CursoProfesor'),
        ),
        migrations.AddField(
            model_name='cursogrupoalumno',
            name='curso_alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='alumnos.CursoAlumno'),
        ),
        migrations.AddField(
            model_name='cursogrupoalumno',
            name='curso_grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='grupos.CursoGrupo'),
        ),
        migrations.AddField(
            model_name='cursogrupo',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='cursos.Curso'),
        ),
        migrations.AddField(
            model_name='cursogrupo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='grupos.Grupo'),
        ),
        migrations.AddField(
            model_name='cursogrupo',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutorias', to='users.CursoProfesor'),
        ),
        migrations.AlterUniqueTogether(
            name='cursogrupo',
            unique_together=set([('curso', 'grupo')]),
        ),
    ]
