# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-24 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0002_auto_20170123_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursogrupoalumno',
            options={'ordering': ['curso_grupo__curso', 'curso_grupo__grupo', 'curso_alumno__alumno'], 'verbose_name': 'Grupos y Alumn@'},
        ),
        migrations.AlterModelOptions(
            name='cursogrupoprofesor',
            options={'ordering': ['curso_grupo__curso', 'curso_grupo__grupo', 'curso_profesor__profesor'], 'verbose_name': 'Grupos y Profesor@'},
        ),
    ]
