# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-22 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0006_prestamo'),
        ('grupos', '0003_auto_20170124_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='nivel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libros.Nivel'),
        ),
    ]
