# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0008_auto_20161019_1142'),
        ('grupos', '0003_cursogrupoalumno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursogrupoalumno',
            options={'ordering': ['curso_grupo__curso', 'alumno__username'], 'verbose_name': 'Alumnos por Grupo y curso'},
        ),
        migrations.AddField(
            model_name='cursogrupoalumno',
            name='alumno',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='alumnos.Alumno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cursogrupoalumno',
            name='curso_grupo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cursogruposalumnos', to='grupos.CursoGrupo'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='cursogrupoalumno',
            unique_together=set([('curso_grupo', 'alumno')]),
        ),
    ]
