# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-22 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0004_grupo_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='libros.Nivel'),
        ),
    ]
