# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 09:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0004_auto_20161019_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursogrupoalumno',
            options={'ordering': ['curso_grupo__curso', 'alumno'], 'verbose_name': 'Alumnos por Grupo y curso'},
        ),
        migrations.AlterField(
            model_name='cursogrupo',
            name='tutor',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tutores', to=settings.AUTH_USER_MODEL),
        ),
    ]
