# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0005_auto_20161019_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursogrupoalumno',
            options={'ordering': ['curso_grupo__curso', 'alumno'], 'verbose_name': 'Grupos y alumno/a'},
        ),
    ]
