# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0008_auto_20161019_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='grupo',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
