# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0010_auto_20161019_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursogrupoprofesor',
            options={'ordering': ['curso_grupo__curso', 'curso_grupo__grupo', 'profesor'], 'verbose_name': 'Grupos y profesore/a'},
        ),
    ]
