# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0011_auto_20161019_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursogrupoalumno',
            options={'ordering': ['curso_grupo__curso', 'curso_grupo__grupo', 'alumno'], 'verbose_name': 'Grupos y alumno/a'},
        ),
    ]
