# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-21 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('area', models.CharField(help_text='Área de conocimiento', max_length=150, verbose_name='Área')),
            ],
            options={
                'ordering': ['area'],
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(help_text='Nombre del autor', max_length=150, verbose_name='Nombre')),
                ('apellidos', models.CharField(help_text='Apellidos del autor', max_length=150, verbose_name='Apellidos')),
            ],
            options={
                'ordering': ['apellidos', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ciclo', models.CharField(help_text='Ciclo de estudios', max_length=50, verbose_name='Ciclo')),
                ('descripcion', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['ciclo'],
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('editorial', models.CharField(help_text='Nombre de la editorial', max_length=150, verbose_name='Editorial')),
            ],
            options={
                'ordering': ['editorial'],
            },
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('estado', models.CharField(choices=[('DISP', 'Disponible'), ('PRES', 'Prestado'), ('DETE', 'Deteriorado'), ('BAJA', 'Dado de baja')], default='DISP', max_length=4)),
                ('codigo_barras', models.CharField(max_length=50, unique=True, verbose_name='Código de barras')),
            ],
            options={
                'verbose_name': 'ejemplar',
                'verbose_name_plural': 'ejemplares',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('titulo', models.CharField(db_index=True, help_text='Título del libro', max_length=150, verbose_name='Título')),
                ('anio_edicion', models.CharField(blank=True, help_text='Año de la edición', max_length=4, verbose_name='Año Edición')),
                ('isbn', models.CharField(blank=True, max_length=50, verbose_name='ISBN')),
                ('codigo_barras', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Código de barras')),
                ('numero_ejemplares', models.SmallIntegerField(default=1, verbose_name='Número de Ejemplares')),
                ('bajas', models.SmallIntegerField(default=0, verbose_name='Número de Ejemplares dados de baja')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio del libro')),
                ('fecha_inicio', models.DateField(blank=True)),
                ('fecha_fin', models.DateField(blank=True)),
                ('area_conocimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libros.Area')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libros.Autor')),
                ('editorial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libros.Editorial')),
            ],
            options={
                'ordering': ['titulo', 'autor'],
                'verbose_name': 'libro',
                'verbose_name_plural': 'libros',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nivel', models.SmallIntegerField(verbose_name='Nivel')),
                ('ciclo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libros.Ciclo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='libro',
            name='nivel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libros.Nivel'),
        ),
        migrations.AddField(
            model_name='ejemplar',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.Libro'),
        ),
    ]
