# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-21 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['autor'], 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='editorial',
            options={'ordering': ['editorial'], 'verbose_name_plural': 'Editoriales'},
        ),
        migrations.AlterModelOptions(
            name='nivel',
            options={'ordering': ['nivel'], 'verbose_name_plural': 'Niveles'},
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='nombre',
            new_name='autor',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='apellidos',
        ),
    ]
