# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-21 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_auto_20170321_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='autor',
            field=models.CharField(help_text='Nombre del autor/es', max_length=150, verbose_name='Autor'),
        ),
    ]
