# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-21 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_auto_20170321_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
