# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-21 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_auto_20170321_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplar',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Código de barras'),
        ),
    ]
