# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-21 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0003_auto_20170124_1203'),
        ('libros', '0005_auto_20170321_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fecha_inicio_prestamo', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin_prestamo', models.DateTimeField(blank=True, null=True)),
                ('curso_grupo_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.CursoGrupoAlumno')),
                ('ejemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.Ejemplar')),
            ],
            options={
                'verbose_name': 'préstamo',
                'verbose_name_plural': 'préstamos',
            },
        ),
    ]
