# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-22 09:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0007_prestamo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
