# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-29 08:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libros', '0008_auto_20170322_1033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejemplar',
            options={'ordering': ('codigo_barras',), 'verbose_name': 'ejemplar', 'verbose_name_plural': 'ejemplares'},
        ),
        migrations.AddField(
            model_name='prestamo',
            name='user_devolucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_dev', to=settings.AUTH_USER_MODEL),
        ),
    ]
