# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-24 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0009_auto_20170329_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['titulo'], 'verbose_name': 'libro', 'verbose_name_plural': 'libros'},
        ),
        migrations.RemoveField(
            model_name='libro',
            name='autor',
        ),
        migrations.AddField(
            model_name='libro',
            name='autor',
            field=models.ManyToManyField(to='libros.Autor'),
        ),
    ]
