# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-25 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0011_auto_20170425_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libros.Autor'),
        ),
    ]
