# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-12 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0015_remove_libro_bajas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplar',
            name='codigo_barras',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True, verbose_name='Código de barras'),
        ),
        migrations.AlterField(
            model_name='ejemplar',
            name='estado',
            field=models.CharField(choices=[('DISP', 'Disponible'), ('PRES', 'Prestado'), ('DETE', 'Deteriorado'), ('BAJA', 'Dado de baja')], db_index=True, default='DISP', max_length=4),
        ),
    ]
