# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-12 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0017_auto_20171112_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='codigo_barras',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True, verbose_name='Código de barras'),
        ),
    ]
